(define (problem p02)
(:domain rubiks-domain02)
(:objects
   wob wbr rby ygo gow oyb ryg wrg gy ry by oy gw rw bw ow rg og ob rb  
)
(:init
    (up_front_left ryg)
    (up_front_right ygo)
    (up_back_left rby)
    (up_back_right oyb)
    (down_front_left wrg)
    (down_front_right gow)
    (down_back_left wbr)
    (down_back_right wob)
    (edge_up_left ry)
    (edge_up_right oy)
    (edge_up_front gy)
    (edge_up_back by)
    (edge_mid_front_left rg)
    (edge_mid_front_right og)
    (edge_mid_back_left rb)
    (edge_mid_back_right ob)
    (edge_down_left rw)
    (edge_down_right ow)
    (edge_down_front gw)
    (edge_down_back bw)
)
(:goal
(and
    (up_front_left ryg)
    (up_front_right ygo)
    (up_back_left rby)
    (up_back_right oyb)
    (down_front_left wrg)
    (down_front_right gow)
    (down_back_left wbr)
    (down_back_right wob)
    (edge_up_left ry)
    (edge_up_right oy)
    (edge_up_front gy)
    (edge_up_back by)
    (edge_mid_front_left rg)
    (edge_mid_front_right og)
    (edge_mid_back_left rb)
    (edge_mid_back_right ob)
    (edge_down_left rw)
    (edge_down_right ow)
    (edge_down_front gw)
    (edge_down_back bw)
)
)
)
