(define (domain rubiks-domain02)
(:requirements :strips)
(:constants
    dummypoint
)
(:predicates
    (up_front_left ?corner)
    (up_front_right ?corner)
    (up_back_left ?corner)
    (up_back_right ?corner)
    (down_front_left ?corner)
    (down_front_right ?corner)
    (down_back_left ?corner)
    (down_back_right ?corner)
    (edge_up_left ?edge)
    (edge_up_right ?edge)
    (edge_up_front ?edge)
    (edge_up_back ?edge)
    (edge_mid_front_left ?edge)
    (edge_mid_front_right ?edge)
    (edge_mid_back_left ?edge)
    (edge_mid_back_right ?edge)
    (edge_down_left ?edge)
    (edge_down_right ?edge)
    (edge_down_front ?edge)
    (edge_down_back ?edge)
)
(:action rotate_R
    :parameters (?corner1 ?corner2 ?corner3 ?corner4 ?edge1 ?edge2 ?edge3 ?edge4)
    :precondition
    (and
      (up_front_right ?corner1)
      (down_front_right ?corner2)
      (up_back_right ?corner3)
      (down_back_right ?corner4)
      (edge_mid_front_right ?edge1)
      (edge_up_right ?edge2)
      (edge_mid_back_right ?edge3)
      (edge_down_right ?edge4)
    )
    :effect
    (and
      (up_front_right ?corner2)
      (down_front_right ?corner4)
      (up_back_right ?corner1)
      (down_back_right ?corner3)
      (not (up_front_right ?corner1))
      (not (down_front_right ?corner2))
      (not (up_back_right ?corner3))
      (not (down_back_right ?corner4))
      (edge_mid_front_right ?edge4)
      (edge_up_right ?edge1)
      (edge_mid_back_right ?edge2)
      (edge_down_right ?edge3)
      (not (edge_mid_front_right ?edge1))
      (not (edge_up_right ?edge2))
      (not (edge_mid_back_right ?edge3))
      (not (edge_down_right ?edge4))
    )
)
)
